In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
damping = 1.0
inf = pow(10,60)
ppg = 3
w = np.random.randint(0,10,(ppg, ppg))

# matrix
alpha = np.zeros((ppg,ppg))
rho = np.zeros((ppg,ppg))
eta = np.zeros((ppg,ppg))
beta = np.zeros((ppg,ppg))

In [10]:
w

array([[0, 2, 7],
       [9, 5, 9],
       [2, 6, 1]])

In [15]:
def update_beta():
    global beta 
    old = np.copy(beta)
    new = w+alpha
    beta = damping*new + (1-damping)*old
    # 
def update_rho():
    global rho 
    old = np.copy(rho)
    
    # 
    # 
    # 
    # 
    
    new = w+eta
    rho = damping*new + (1-damping)*old
    
def update_alpha(): # 행이 보는 입장
    global alpha
    old = np.copy(alpha)
    new = np.copy(alpha)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = np.copy(rho)
            tmp[i,j] = -inf
            new[i,j] = -tmp[i,:].max()
    alpha = damping*new + (1-damping)*old
    
def update_eta(): # 열이 보는 입장
    global eta
    old = np.copy(eta)
    new = np.copy(eta)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = np.copy(beta)
            tmp[i,j] = -inf
            new[i,j] = -tmp[:,j].max()
    eta = damping*new + (1-damping)*old

In [12]:
for i in range (0,10):
        
    print("[Iter : {0}] Update Alpha\n".format(i))     
    update_alpha()
    print(alpha)
    print("\n")
    print("[Iter : {0}] Update eta\n".format(i))   
    update_eta()
    print(eta)
    print("\n")    
    print("[Iter : {0}] Update rho\n".format(i))   
    update_rho()
    print(rho)
    print("\n")    
    print("[Iter : {0}] Update beta\n".format(i))   
    update_beta()
    print(beta)
    print("\n")    

[Iter : 0] Update Alpha

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[Iter : 0] Update eta

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[Iter : 0] Update rho

[[0. 2. 7.]
 [9. 5. 9.]
 [2. 6. 1.]]


[Iter : 0] Update beta

[[0. 2. 7.]
 [9. 5. 9.]
 [2. 6. 1.]]


[Iter : 1] Update Alpha

[[-7. -7. -2.]
 [-9. -9. -9.]
 [-6. -2. -6.]]


[Iter : 1] Update eta

[[-9. -6. -9.]
 [-2. -6. -7.]
 [-9. -5. -9.]]


[Iter : 1] Update rho

[[-9. -4. -2.]
 [ 7. -1.  2.]
 [-7.  1. -8.]]


[Iter : 1] Update beta

[[-7. -5.  5.]
 [ 0. -4.  0.]
 [-4.  4. -5.]]


[Iter : 2] Update Alpha

[[ 2.  2.  4.]
 [-2. -7. -7.]
 [-1.  7. -1.]]


[Iter : 2] Update eta

[[-0. -4. -0.]
 [ 4. -4. -5.]
 [-0.  4. -5.]]


[Iter : 2] Update rho

[[ 0. -2.  7.]
 [13.  1.  4.]
 [ 2. 10. -4.]]


[Iter : 2] Update beta

[[ 2.  4. 11.]
 [ 7. -2.  2.]
 [ 1. 13.  0.]]


[Iter : 3] Update Alpha

[[ -7.  -7.   0.]
 [ -4. -13. -13.]
 [-10.  -2. -10.]]


[Iter : 3] Update eta

[[ -7. -13.  -2.]
 [ -2. -13. -11.]
 [ -7.  -4. -11.]]


[Iter : 3] Up

In [13]:
print(eta+alpha+w)

[[-32. -32.  21.]
 [ 21. -35. -33.]
 [-32.  18. -37.]]


In [14]:
D = eta+alpha+w
for i in range (0,ppg):
    for j in range (0,ppg):
        if(D[i,j]==D[i,:].max()):
            D[i,:] = 0
            D[i,j] = 1
            
print("Match result: \n",D)

Match result: 
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
