In [15]:
import numpy as np
#np.random.seed(seed=1)

inf = pow(10,60)
damping = 0.5 # ratio of the new values
ppg = 4 #people per group
#w = np.random.randint(1,10,(ppg,ppg))
w = np.array([[8,2,8,1],[7,8,7,2],[1,2,9,9],[4,9,8,4]])
print("w:\n",w)

alpha = np.ones((ppg,ppg,2))
rho = np.ones((ppg,ppg,2))
eta = np.ones((ppg,ppg,2))
beta = np.ones((ppg,ppg,2))

def update_rho():
    global rho
    for i in range (0,ppg):
        for j in range(0,ppg):
            rho[i,j,1]=min(eta[i,j,1],w[i,j])
            rho[i,j,0]=eta[i,j,0]

def update_beta():
    global beta
    for i in range (0,ppg):
        for j in range(0,ppg):
            beta[i,j,1]=min(alpha[i,j,1],w[i,j])
            beta[i,j,0]=alpha[i,j,0]
    
def update_alpha():
    global alpha
    #alpha(1)
    for i in range(0,ppg):
        tmp = np.copy(rho)
        tmp[i,:,0] = inf
        for j in range(0,ppg):
            #alpha[i,j,1]=min(w[i,j],min(tmp[:,j,0]))
            alpha[i,j,1]=min(tmp[:,j,0])
    #alpha(0)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = list()
            for k in range(0,ppg):
                if (k!=i):
                    tmp2 = list()
                    tmp3 = list()
                    tmp2.append(rho[k,j,1])
                    for k2 in range(0,ppg):
                        if (k2!=k and k2!=i):     
                            tmp3.append(rho[k2,j,0])
                    tmp2.append(min(tmp3))
                    tmp.append(min(tmp2))        
            alpha[i,j,0] = max(tmp)
            
def update_eta():
    global eta
    #eta(1)
    for j in range(0,ppg):
        tmp = np.copy(beta)
        tmp[:,j,0] = inf
        for i in range(0,ppg):
            #eta[i,j,1]=min(w[i,j],min(tmp[i,:,0]))
            eta[i,j,1]=min(tmp[i,:,0])
    
    #eta(0)
    for j in range(0,ppg):
        for i in range(0,ppg):
            tmp = list()
            for k in range(0,ppg):
                if (k!=j):
                    tmp2 = list()
                    tmp3 = list()
                    tmp2.append(beta[i,k,1])
                    for k2 in range(0,ppg):
                        if (k2!=k and k2!=j):     
                            tmp3.append(beta[i,k2,0])
                    tmp2.append(min(tmp3))
                    tmp.append(min(tmp2))        
            eta[i,j,0] = max(tmp)

w:
 [[8 2 8 1]
 [7 8 7 2]
 [1 2 9 9]
 [4 9 8 4]]


In [16]:
alpha[:,:,1] = np.copy(w)
eta[:,:,1] = np.copy(w)
beta[:,:,1] = np.copy(w)
rho[:,:,1] = np.copy(w)

alpha[:,:,0] = np.max(w)
eta[:,:,0] = np.max(w)
beta[:,:,0] = np.max(w)
rho[:,:,0] = np.max(w)

In [17]:
for i in range (0,100):
    update_rho()
    update_beta()
    update_alpha()
    update_eta()
    
    print("\n------------",i)
    print("rho(1):\n",rho[:,:,1])
    print("rho(0):\n",rho[:,:,0])
    print("beta(1):\n",beta[:,:,1])
    print("beta(0):\n",beta[:,:,0])
    print("alpha(1):\n",alpha[:,:,1])
    print("alpha(0):\n",alpha[:,:,0])
    print("eta(1):\n",eta[:,:,1])
    print("eta(0):\n",eta[:,:,0])


------------ 0
rho(1):
 [[8. 2. 8. 1.]
 [7. 8. 7. 2.]
 [1. 2. 9. 9.]
 [4. 9. 8. 4.]]
rho(0):
 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
beta(1):
 [[8. 2. 8. 1.]
 [7. 8. 7. 2.]
 [1. 2. 9. 9.]
 [4. 9. 8. 4.]]
beta(0):
 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
alpha(1):
 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
alpha(0):
 [[7. 9. 9. 9.]
 [8. 9. 9. 9.]
 [8. 9. 8. 4.]
 [8. 8. 9. 9.]]
eta(1):
 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
eta(0):
 [[8. 8. 8. 8.]
 [8. 7. 8. 8.]
 [9. 9. 9. 9.]
 [9. 8. 9. 9.]]

------------ 1
rho(1):
 [[8. 2. 8. 1.]
 [7. 8. 7. 2.]
 [1. 2. 9. 9.]
 [4. 9. 8. 4.]]
rho(0):
 [[8. 8. 8. 8.]
 [8. 7. 8. 8.]
 [9. 9. 9. 9.]
 [9. 8. 9. 9.]]
beta(1):
 [[8. 2. 8. 1.]
 [7. 8. 7. 2.]
 [1. 2. 9. 9.]
 [4. 9. 8. 4.]]
beta(0):
 [[7. 9. 9. 9.]
 [8. 9. 9. 9.]
 [8. 9. 8. 4.]
 [8. 8. 9. 9.]]
alpha(1):
 [[8. 7. 8. 8.]
 [8. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 7. 8. 8.]]
alpha(0):
 [[7. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8.

 [4. 7. 8. 4.]]
beta(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]
alpha(1):
 [[8. 7. 7. 7.]
 [7. 8. 7. 7.]
 [7. 7. 7. 8.]
 [7. 7. 8. 7.]]
alpha(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]
eta(1):
 [[8. 7. 7. 7.]
 [7. 8. 7. 7.]
 [4. 4. 4. 8.]
 [7. 7. 8. 7.]]
eta(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 7.]
 [8. 8. 7. 8.]]

------------ 67
rho(1):
 [[8. 2. 7. 1.]
 [7. 8. 7. 2.]
 [1. 2. 4. 8.]
 [4. 7. 8. 4.]]
rho(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 7.]
 [8. 8. 7. 8.]]
beta(1):
 [[8. 2. 7. 1.]
 [7. 8. 7. 2.]
 [1. 2. 7. 8.]
 [4. 7. 8. 4.]]
beta(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]
alpha(1):
 [[8. 7. 7. 7.]
 [7. 8. 7. 7.]
 [7. 7. 7. 8.]
 [7. 7. 8. 7.]]
alpha(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]
eta(1):
 [[8. 7. 7. 7.]
 [7. 8. 7. 7.]
 [4. 4. 4. 8.]
 [7. 7. 8. 7.]]
eta(0):
 [[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 7.]
 [8. 8. 7. 8.]]

------------ 68
rho(1):
 [[8. 2. 7. 1.]
 [7. 

In [18]:
g = np.zeros([ppg,ppg,2])
for i in range(0,ppg):
    for j in range(0,ppg):
        g[i,j,1]=min(eta[i,j,1],beta[i,j,1])
        g[i,j,0]=min(eta[i,j,0],beta[i,j,0])
print(g[:,:,1])
print(g[:,:,0])
print("\n\n",g[:,:,1]-g[:,:,0])

print("\n-------------------\n")

b = np.zeros([ppg,ppg,2])
for i in range(0,ppg):
    for j in range(0,ppg):
        b[i,j,1]=min(rho[i,j,1],alpha[i,j,1])
        b[i,j,0]=min(rho[i,j,0],alpha[i,j,0])
print(b[:,:,1])
print(b[:,:,0])
print("\n\n",b[:,:,1]-b[:,:,0])

[[8. 2. 7. 1.]
 [7. 8. 7. 2.]
 [1. 2. 4. 8.]
 [4. 7. 8. 4.]]
[[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]


 [[ 1. -6. -1. -7.]
 [-1.  1. -1. -6.]
 [-7. -6. -4.  4.]
 [-4. -1.  1. -4.]]

-------------------

[[8. 2. 7. 1.]
 [7. 8. 7. 2.]
 [1. 2. 4. 8.]
 [4. 7. 8. 4.]]
[[7. 8. 8. 8.]
 [8. 7. 8. 8.]
 [8. 8. 8. 4.]
 [8. 8. 7. 8.]]


 [[ 1. -6. -1. -7.]
 [-1.  1. -1. -6.]
 [-7. -6. -4.  4.]
 [-4. -1.  1. -4.]]
