In [157]:
import numpy as np
#np.random.seed(seed=1)

inf = pow(10,60)
damping = 1.0 # ratio of the new values
ppg = 4 #people per group
w = np.random.randint(1,10,(ppg,ppg))
# w = np.array([[8,2,8,1],[7,8,7,2],[1,2,9,9],[4,9,8,4]])
print("w:\n",w)

alpha = np.zeros((ppg,ppg))
rho = np.zeros((ppg,ppg))
eta = np.zeros((ppg,ppg))
beta = np.zeros((ppg,ppg))

#variables: local for read-only, global for updating 
# def update_beta():
#     global beta 
#     old = np.copy(beta)
#     new = np.copy(beta)
#     for i in range(0,ppg):
#         for j in range(0,ppg):
#             tmp = np.copy(w+alpha)
#             tmp[i,j] = -inf
#             new[i,j] = w[i,j] - tmp[i,:].max()
#     beta = damping*new + (1-damping)*old
    
# def update_rho():
#     global rho 
#     old = np.copy(rho)
#     new = np.copy(rho)
#     for i in range(0,ppg):
#         for j in range(0,ppg):
#             tmp = np.copy(w+eta)
#             tmp[i,j] = -inf
#             new[i,j] = w[i,j] - tmp[i,:].max()
#     rho = damping*new + (1-damping)*old
    
def update_beta():
    global beta 
    old = np.copy(beta)
    new = w+alpha
    beta = damping*new + (1-damping)*old
    
def update_rho():
    global rho 
    old = np.copy(rho)
    new = w+eta
    rho = damping*new + (1-damping)*old
    
def update_alpha():
    global alpha
    old = np.copy(alpha)
    new = np.copy(alpha)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = np.copy(rho)
            tmp[i,j] = -inf
            new[i,j] = -tmp[i,:].max()
    alpha = damping*new + (1-damping)*old
    
def update_eta():
    global eta
    old = np.copy(eta)
    new = np.copy(eta)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = np.copy(beta)
            tmp[i,j] = -inf
            new[i,j] = -tmp[:,j].max()
    eta = damping*new + (1-damping)*old
    

w:
 [[2 7 6 5]
 [5 3 4 5]
 [1 4 5 6]
 [1 7 8 1]]


In [158]:
for i in range (0,10):
    
    update_alpha()
    update_eta()
    update_rho()
    update_beta()
    
#     print("rho:\n",rho)
#     print("beta:\n",beta)
#     print("alpha:\n",alpha)
#     print("eta:\n",eta)

In [159]:
print(eta+alpha+w)

[[-19.   2. -16. -17.]
 [  6. -20. -19. -18.]
 [-19. -17. -16.   4.]
 [-20. -15.   3. -21.]]


In [160]:
D = eta+alpha+w
for i in range (0,ppg):
    for j in range (0,ppg):
        if(D[i,j]==D[i,:].max()):
            D[i,:] = 0
            D[i,j] = 1
            
print("Match result: \n",D)

Match result: 
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
