In [43]:
import numpy as np

In [44]:
# Declare Variables and matrix

# Variables
infinity = pow(10,60)
damping = 1.0
ppg = 4 # 4 by 4 people per group
w = np.random.randint(1,10,(ppg,ppg)) # weight matrix

# Matrix
alpha = np.zeros((ppg,ppg))
rho = np.zeros((ppg,ppg))
eta = np.zeros((ppg,ppg))
beta = np.zeros((ppg,ppg))

In [45]:
w

array([[8, 2, 2, 5],
       [6, 8, 5, 3],
       [9, 5, 9, 6],
       [4, 8, 6, 5]])

In [46]:
class MaxSumAlgorithm:
    
    def __init__ (self):
        pass
    def update_alpha():
        global alpha
        old = np.copy(alpha)
        new = np.copy(alpha)
        for i in range(0,ppg):
            for j in range(0, ppg):
                tmp = np.copy(rho)
                tmp[i,j] = -infinity
                new[i,j] = -tmp[i, :].max()
        alpha = damping*new + (1-damping)*old
        pass
    def update_beta():
        global beta
        old = np.copy(beta)
        new = np.copy(beta)
        for i in range(0,ppg):
            for j in range(0,ppg):
                tmp = np.copy(eta)
                tmp[i,j] = -infinity
                new[i,j] = -tmp[:,j].max()
        beta = damping*new + (1-damping)*old   
        pass
    def update_rho():
        global rho 
        old = np.copy(rho)
        new = w+alpha
        rho = damping*new + (1-damping)*old
        pass
    def update_eta():
        global eta 
        old = np.copy(eta)
        new = w + beta
        eta = damping*new + (1-damping)*old
        pass
    

In [47]:
def __init__ (self):
    pass
def update_alpha():
    global alpha
    old = np.copy(alpha)
    new = np.copy(alpha)
    for i in range(0,ppg):
        for j in range(0, ppg):
            tmp = np.copy(rho)
            tmp[i,j] = -infinity
            new[i,j] = -tmp[i, :].max()
    alpha = damping*new + (1-damping)*old
    pass
def update_beta():
    global beta
    old = np.copy(beta)
    new = np.copy(beta)
    for i in range(0,ppg):
        for j in range(0,ppg):
            tmp = np.copy(eta)
            tmp[i,j] = -infinity
            new[i,j] = -tmp[:,j].max()
    beta = damping*new + (1-damping)*old   
    pass
def update_rho():
    global rho 
    old = np.copy(rho)
    new = w+alpha
    rho = damping*new + (1-damping)*old
    pass
def update_eta():
    global eta 
    old = np.copy(eta)
    new = w + beta
    eta = damping*new + (1-damping)*old
    pass

In [48]:
ms = MaxSumAlgorithm()

for i in range(10):
    update_alpha()
    update_rho()
    update_beta()
    update_eta()

In [49]:
print(rho+alpha+w)

[[ 30. -36. -36. -30.]
 [-20.  20. -22. -26.]
 [  0.  -8.   0.  -6.]
 [-24.  20. -20. -22.]]


In [50]:
D = rho+alpha+w
for i in range (0,ppg):
    for j in range (0,ppg):
        if(D[i,j]==D[i,:].max()):
            D[i,:] = 0
            D[i,j] = 1
            
print("Match result: \n",D)

Match result: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
