In [19]:
#Library

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import random as rd

In [4]:
class gradientDescent:
    def __init__(self):
        self.example = 0
        pass

In [ ]:
#GD Code
n = 20
x = [i for i in range(n)]
y = [i + np.random.rand()*7 for i in range(n)]

w = np.random.rand()
b = np.random.rand()

lr = 0.0005 # learning Rate
iter = 0
maxIter = 1000
loss = []

while True:
    L = 0
    shuffle = list(range(n))
    rd.shuffle(shuffle)
    
    for idx in range(n):
        k = shuffle[idx]
        s = w * x[k] + b*1
        L = L + 1/2 * (s - y[k])**2
        
        #Chain Rule
        dL_ds = s - y[k]
        ds_dw = x[k]
        ds_db = 1
        
        dL_dw = dL_ds * ds_db
        dL_db = dL_ds * ds_dw
        
        w = w - lr*dL_dw
        b = w - lr*dL_db
        
    iter += 1
    loss.append(L)
    y_regress = [w * i + b for i in x]
    
    if iter > maxIter: break
    
#Loss
plt.plot(range(iter), loss, 'b')    
plt.show()

# Prediction
plt.plot(x, y_regress, 'r')
plt.show()

In [28]:
#Adapting auto Differential to Gradient Descent

n = 20
x = [[float(i) for i in range(n)]]
y = [[i + np.random.rand()*7 for i in range(n)]]

# tf로 처리하기 위해서는 tf.Variable(tf.random.normal((1,1))처리)
w = tf.Variable(tf.random.normal((1,1)), name = 'w')
b = tf.Variable(tf.random.normal((1,1)), name = 'b')

iter = 0
maxIter = 20
lr = tf.constant(0.0005)
Loss = []

while True:
    L = 0
    for k in range(np.size(x,1)):
        X = [[x[0][k]]]
        Y = [[y[0][k]]]
        
        with tf.GradientTape() as tape:
            f = X * w + b
            print("f:",f)
            loss = tf.reduce_mean((f - Y)**2)
            
        [dl_dw, dl_db] = tape.gradient(loss, [w,b])
        print("dl_dw", dl_dw)
        print("dl_db", dl_db)
        print(type(dl_dw))
        print(type(lr))       
        L = L + loss
        
        w.assign_add(-lr * dl_dw)
        b.assign_add(-lr * dl_db)
        print(w)
        print(b)
        
    iter+= 1
    Loss.append(L.numpy())
    
    w_ = w.numpy()
    b_ = b.numpy()
    print(w_[0][0])
    print(b_[0][0])
    y_regress = [w_[0][0]*i+b_[0][0] for i in x[0]]
    print(x[0])
    print(y_regress)
        
    if iter > maxIter : break

f: tf.Tensor([[-0.20433463]], shape=(1, 1), dtype=float32)
dl_dw tf.Tensor([[-0.]], shape=(1, 1), dtype=float32)
dl_db tf.Tensor([[-3.4631436]], shape=(1, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<tf.Variable 'w:0' shape=(1, 1) dtype=float32, numpy=array([[0.13247202]], dtype=float32)>
<tf.Variable 'b:0' shape=(1, 1) dtype=float32, numpy=array([[-0.20260306]], dtype=float32)>
f: tf.Tensor([[-0.07013103]], shape=(1, 1), dtype=float32)
dl_dw tf.Tensor([[-5.38596]], shape=(1, 1), dtype=float32)
dl_db tf.Tensor([[-5.38596]], shape=(1, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<tf.Variable 'w:0' shape=(1, 1) dtype=float32, numpy=array([[0.135165]], dtype=float32)>
<tf.Variable 'b:0' shape=(1, 1) dtype=float32, numpy=array([[-0.19991007]], dtype=float32)>
f: tf.Tensor([[0.07041994]], shape=(1, 1), dtype=float32)
dl_dw tf.Te